In [3]:
import numpy as np

In [ ]:
# Create 1D Array and operations on this

In [4]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = np.array ([7,6,5,4,3,2,1,0])
b

array([7, 6, 5, 4, 3, 2, 1, 0])

In [7]:
print('Shape: ', b.shape)
print('Datatype: ', b.dtype)
print('Size: ', b.size)
print('Num Dimensions: ', b.ndim)

Shape:  (8,)
Datatype:  int32
Size:  8
Num Dimensions:  1


In [20]:
 np.arange(20)



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [22]:
# Arithmetic Operations on array

In [25]:
s = np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
s+a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
s-a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
s*a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [30]:
s+4


array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [31]:
s**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [32]:
# Create a 2d array

In [33]:
List1= [[4,5,8,7],[1,2,3,6],[6,4,9,2]]
List1

[[4, 5, 8, 7], [1, 2, 3, 6], [6, 4, 9, 2]]

In [35]:
L= np.array(List1)
L

array([[4, 5, 8, 7],
       [1, 2, 3, 6],
       [6, 4, 9, 2]])

In [38]:
print('Shape: ', L.shape)
print('Datatype: ', L.dtype)
print('Size: ', L.size)
print('Num Dimensions: ', L.ndim)

Shape:  (3, 4)
Datatype:  int32
Size:  12
Num Dimensions:  2


In [39]:
print("Mean value is: ", L.mean())
print("Max value is: ",L.max())
print("Min value is: ", L.min())

Mean value is:  4.75
Max value is:  9
Min value is:  1
